### ISSUE TITLE
Scoop-search --hook doesn't return anything

### ISSUE THREAD

**Issue by longhoang0304** [shilangyu/scoop-search#51] opened 2024-02-18 16:28 UTC
## Test environment
- Version: 1.4.1 (the latest one)
- Windows 11 22H2 - Build 22621.3155
- Windows terminal
- Shell: powershell 6 + powershell 7

## Description:
![image](https://github.com/shilangyu/scoop-search/assets/11588927/3fc91538-cfe5-42f0-bbe4-b26f5ee4c30d)

`&scoop-search --hook` return empty string and cannot work with `Invoke-Expression`

I've tried with `scoop-search --hook` but still had the same problem.

## Expected output:
```
function scoop { if ($args[0] -eq "search") { scoop-search.exe @($args | Select-Object -Skip 1) } else { scoop.ps1 @args } }
```

---------

I've tried to build it on my machine and it works as expected (zig v0.11). After investigation, it seems that the release binary has a bug in it. One instructor is mis-compiled and triggered the kernel exception on my machine.

My built binary: [scoop-search.zip](https://github.com/shilangyu/scoop-search/files/14323386/scoop-search.zip)
Virus total: https://www.virustotal.com/gui/file/ff01575f8ab0777c56e848d9ae8862ac90f98b90d3eab0433af1f600093464ef?nocache=1

**Comment by shilangyu** [comment] 2024-02-18 17:18
Duplicate of #46. The conclusion is the same, some instruction is mis-compiled. Unfortunately I have absolutely no idea why that is happening and how to avoid it, any ideas?

**Closed by shilangyu** 2024-02-18 17:18 UTC

**Comment by longhoang0304** [comment] 2024-02-18 21:52
> any ideas?

So sorry I didn't go that far. But let me follow up with the other issue. Thank you.
